name: steinbock-snakemake
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - abseil-cpp=20210324.2=h9c3ff4c_0
  - absl-py=2.1.0=pyhd8ed1ab_0
  - adjusttext=1.2.0=pyhd8ed1ab_0
  - aiohttp=3.9.5=py39hd1e30aa_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - amply=0.1.6=py39h06a4308_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - beautifulsoup4=4.12.3=py39h06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - bioservices=1.11.2=pyhd8ed1ab_1
  - blas=1.0=openblas
  - blinker=1.8.2=pyhd8ed1ab_0
  - bottleneck=1.3.7=py39ha9d4c09_0
  - brokenaxes=0.4.2=pyhd8ed1ab_0
  - brotli=1.0.9=he6710b0_2
  - brotli-python=1.1.0=py39h3d6467e_1
  - bx-python=0.11.0=py39had678e3_3
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.7.2=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.3=pyhd8ed1ab_0
  - certifi=2024.7.4=py39h06a4308_0
  - cffi=1.16.0=py39h7a31438_0
  - chardet=4.0.0=py39h06a4308_1003
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - coin-or-cbc=2.10.10=hd28fd6d_0
  - coin-or-cgl=0.60.5=h3cb4718_0
  - coin-or-clp=1.17.7=h4e0f3ec_0
  - coin-or-osi=0.108.7=h3cb4718_0
  - coin-or-utils=2.11.6=h4e0f3ec_0
  - coincbc=2.10.10=0_metapackage
  - colorama=0.4.6=py39h06a4308_0
  - coloredlogs=15.0.1=py39h06a4308_2
  - colormap=1.0.1=py_2
  - colormath=3.0.0=py_2
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=39.0.0=py39hd598818_0
  - cuda-version=11.0=h6b8d8af_3
  - cudatoolkit=11.0.3=h7761cd4_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - datrie=0.8.2=py39h27cfd23_0
  - deprecated=1.2.13=py39h06a4308_0
  - docopt=0.6.2=py39h06a4308_1
  - dpath=2.2.0=pyha770c72_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.1=py39hd1e30aa_0
  - future=0.18.3=py39h06a4308_0
  - gast=0.5.4=pyhd8ed1ab_0
  - gevent=23.9.1=py39h5eee18b_0
  - giflib=5.2.2=hd590300_0
  - gitpython=3.1.43=py39h06a4308_0
  - google-auth=2.30.0=pyhff2d567_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - greenlet=3.0.1=py39h6a678d5_0
  - grequests=0.6.0=pyh9f0ad1d_0
  - grpc-cpp=1.43.2=h9e046d8_3
  - grpcio=1.43.0=py39hff7568b_0
  - gseapy=1.1.3=py39h5b94c0b_1
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.9.0=nompi_py39h4dfffb9_100
  - hdf5=1.14.0=nompi_h5231ba7_103
  - hpack=4.0.0=pyh9f0ad1d_0
  - humanfriendly=10.0=py39h06a4308_1
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - itolapi=4.1.4=pyhdfd78af_0
  - jinja2=3.1.4=py39h06a4308_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - joblib=1.4.2=py39h06a4308_0
  - jpeg=9e=h0b41bf4_3
  - jupyter_core=5.7.2=py39h06a4308_0
  - keras=2.8.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=hf9c8cef_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=hf3520f5_3
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=22_linux64_openblas
  - libcblas=3.9.0=22_linux64_openblas
  - libcurl=7.87.0=h6312ad2_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h77fa898_8
  - libgfortran-ng=13.2.0=h69a702a_8
  - libgfortran5=13.2.0=h3d2ce59_8
  - libgomp=13.2.0=h77fa898_8
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=22_linux64_openblas
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=3.19.6=h3eb15da_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=13.2.0=hc0a3c3a_8
  - libtiff=4.2.0=hecacb30_2
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxml2=2.10.3=hca2bb57_4
  - libxslt=1.1.37=h873f0b0_0
  - libzlib=1.2.13=h4ab18f5_6
  - lzstring=1.0.4=py_1001
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py39hd1e30aa_0
  - matplotlib-venn=0.11.10=pyhd8ed1ab_0
  - mock=4.0.3=pyhd3eb1b0_0
  - multidict=6.0.5=py39hd1e30aa_0
  - multiqc=1.11=pyhdfd78af_0
  - nccl=2.18.3.1=h17a0586_0
  - ncurses=6.5=h59595ed_0
  - networkx=3.2.1=py39h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.100=hca3bf56_0
  - numexpr=2.8.7=py39h286c3b5_0
  - numpy=1.23.0=py39hba7629e_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.4.0=h9ca470c_2
  - openssl=1.1.1w=h7f8727e_0
  - opt_einsum=3.3.0=pyhc1e730c_2
  - packaging=24.1=py39h06a4308_0
  - patsy=0.5.6=py39h06a4308_0
  - pip=24.0=pyhd8ed1ab_0
  - plotly=5.22.0=py39h2f386ee_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - protobuf=3.19.6=py39h227be39_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulp=2.7.0=py39hf3d152e_1
  - pyasn1=0.6.0=pyhd8ed1ab_0
  - pyasn1-modules=0.4.0=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pykwalify=1.8.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pysam=0.21.0=py39h9abd093_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.15=h47a2c10_0_cpython
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-fastjsonschema=2.16.2=py39h06a4308_0
  - python-flatbuffers=24.3.25=pyh59ac667_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python_abi=3.9=4_cp39
  - pytz=2024.1=py39h06a4308_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.1=py39h5eee18b_0
  - re2=2022.02.01=h9c3ff4c_0
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - requests_cache=0.4.13=py_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - rich=13.7.1=py39h06a4308_0
  - rich-click=1.8.3=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scipy=1.13.1=py39haf93ffa_0
  - seaborn=0.13.2=py39h06a4308_0
  - selenium=3.141.0=py39h27cfd23_1000
  - sequana=0.16.4=pyhdfd78af_0
  - setuptools=70.0.0=pyhd8ed1ab_0
  - simplejson=3.17.6=py39h7f8727e_0
  - six=1.16.0=pyh6c4a22f_0
  - smart_open=5.2.1=py39h06a4308_0
  - snakemake-minimal=7.32.4=pyhdfd78af_1
  - snappy=1.1.10=hdb0a2a9_1
  - soupsieve=2.5=py39h06a4308_0
  - spectra=0.0.11=py_1
  - sqlite=3.46.0=h6d4b2fc_0
  - statsmodels=0.14.0=py39ha9d4c09_0
  - stopit=1.1.2=py_0
  - suds-community=1.1.2=pyhd8ed1ab_0
  - tabulate=0.9.0=py39h06a4308_0
  - tenacity=8.2.3=py39h06a4308_0
  - tensorboard=2.8.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.6.1=py39hd97740a_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.8.0=cuda110py39hcfb7b87_0
  - tensorflow-base=2.8.0=cuda110py39h3c9bc52_0
  - tensorflow-estimator=2.8.0=cuda110py39ha53fd0e_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - threadpoolctl=3.5.0=py39h2f386ee_0
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=py39h06a4308_0
  - toposort=1.10=pyhd8ed1ab_0
  - tqdm=4.66.4=py39h2f386ee_0
  - traitlets=5.14.3=py39h06a4308_0
  - unicodedata2=15.1.0=py39h5eee18b_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - upsetplot=0.9.0=pyhd8ed1ab_0
  - vcfpy=0.13.8=pyhdfd78af_0
  - werkzeug=3.0.3=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - wrapt=1.16.0=py39hd1e30aa_0
  - xlrd=2.0.1=pyhd3eb1b0_1
  - xmltodict=0.13.0=py39h06a4308_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.4=py39hd1e30aa_0
  - yte=1.5.4=pyha770c72_0
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zope=1.0=py39h06a4308_1
  - zope.event=5.0=py39h06a4308_0
  - zope.interface=5.4.0=py39h7f8727e_0
  - zstandard=0.22.0=py39h81c9582_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - aiobotocore==2.11.2
      - aioitertools==0.11.0
      - alabaster==0.7.16
      - anndata==0.10.7
      - annotated-types==0.7.0
      - anyio==4.4.0
      - app-model==0.2.7
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.7.1
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - async-lru==2.0.4
      - babel==2.15.0
      - bleach==6.1.0
      - botocore==1.34.19
      - build==1.2.1
      - cachey==0.2.1
      - click-log==0.4.0
      - cloudpickle==3.0.0
      - colorcet==3.1.0
      - colorlog==6.8.2
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - cython==0.29.37
      - dask==2024.5.2
      - dask-expr==1.1.2
      - dask-image==2024.5.3
      - datashader==0.16.3
      - debugpy==1.8.1
      - decorator==5.1.1
      - deepcell==0.12.6
      - deepcell-toolbox==0.12.1
      - deepcell-tracking==0.6.4
      - defusedxml==0.7.1
      - distributed==2024.5.2
      - docstring-parser==0.16
      - docutils==0.20.1
      - easydev==0.13.2
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - fcsparser==0.2.8
      - fcswrite==0.6.2
      - flake8==7.1.0
      - flask==3.0.3
      - fonttools==4.53.0
      - fqdn==1.5.1
      - freetype-py==2.4.0
      - fsspec==2023.6.0
      - geopandas==1.0.1
      - get-annotations==0.1.2
      - gitdb==4.0.11
      - h11==0.14.0
      - heapdict==1.0.1
      - hsluv==5.0.4
      - httpcore==1.0.5
      - httpx==0.27.0
      - imagecodecs==2024.6.1
      - imageio==2.34.1
      - imagesize==1.4.1
      - importlib-resources==6.4.0
      - in-n-out==0.2.1
      - ipykernel==6.29.4
      - ipython==8.18.1
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.1
      - jmespath==1.0.1
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - lamin-utils==0.13.2
      - lazy-loader==0.4
      - legacy-api-wrap==1.4
      - line-profiler==4.1.3
      - llvmlite==0.42.0
      - locket==1.0.0
      - lxml==5.2.2
      - lxml-html-clean==0.1.1
      - magicgui==0.8.3
      - markdown-it-py==3.0.0
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.0.2
      - msgpack==1.0.8
      - multipledispatch==1.0.0
      - multiscale-spatial-image==1.0.0
      - napari==0.4.19.post1
      - napari-console==0.0.9
      - napari-plugin-engine==0.2.0
      - napari-svg==0.1.10
      - natsort==8.4.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - npe2==0.7.5
      - numba==0.59.1
      - numcodecs==0.12.1
      - numpydoc==1.7.0
      - ome-zarr==0.9.0
      - opencv-python-headless==4.10.0.82
      - overrides==7.7.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - param==2.1.1
      - parse==1.20.2
      - parso==0.8.4
      - partd==1.4.2
      - pexpect==4.9.0
      - PhenoGraph==1.5.7
      - pillow==10.3.0
      - pims==0.7
      - pint==0.23
      - plac==1.4.3
      - platformdirs==4.2.2
      - pooch==1.8.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - psutil==5.9.8
      - psygnal==0.11.1
      - pure-eval==0.2.2
      - pyarrow==17.0.0
      - pycodestyle==2.12.0
      - pyconify==0.1.6
      - pyct==0.5.0
      - pydantic==2.7.4
      - pydantic-compat==0.1.2
      - pydantic-core==2.18.4
      - pydot==1.4.2
      - pyflakes==3.2.0
      - pygments==2.18.0
      - pynndescent==0.5.13
      - pyogrio==0.9.0
      - pyopengl==3.1.6
      - pyopengl-accelerate==3.1.6
      - pyparsing==3.1.2
      - pyproj==3.6.1
      - pyproject-hooks==1.1.0
      - pyside6==6.7.2
      - pyside6-addons==6.7.2
      - pyside6-essentials==6.7.2
      - python-json-logger==2.0.7
      - pywavelets==1.6.0
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - readfcs==1.1.8
      - readimc==0.7.0
      - referencing==0.35.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - s3fs==0.6.0
      - scanpy==1.10.2
      - scikit-image==0.19.3
      - scikit-learn==1.5.0
      - send2trash==1.8.3
      - sequana-pipetools==1.0.2
      - sequanix==0.2.0
      - session-info==1.0.0
      - shapely==2.0.5
      - shellingham==1.5.4
      - shiboken6==6.7.2
      - slicerator==1.1.0
      - smart-open==7.0.4
      - smmap==5.0.1
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sopa==1.1.1
      - sortedcontainers==2.4.0
      - spatial-image==1.1.0
      - spatialdata==0.2.1
      - spatialdata-io==0.1.3.post0
      - spektral==1.0.6
      - sphinx==7.3.7
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - stack-data==0.6.3
      - stdlib-list==0.10.0
      - steinbock==0.16.3
      - superqt==0.6.7
      - tblib==3.0.0
      - tensorflow-addons==0.16.1
      - terminado==0.18.1
      - tifffile==2024.5.22
      - tinycss2==1.3.0
      - tomli-w==1.0.0
      - toolz==0.12.1
      - tornado==6.4.1
      - typeguard==4.0.0
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - umap-learn==0.5.2
      - uri-template==1.3.0
      - urllib3==1.25.4
      - versionix==0.2.4
      - vispy==0.14.2
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.11
      - xarray==2024.6.0
      - xarray-dataclasses==1.8.0
      - xarray-datatree==0.0.14
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - xtiff==0.7.9
      - zarr==2.18.2
      - zict==3.0.0
variables:
  STEINBOCK_MASK_DTYPE: uint32
  TF_FORCE_GPU_ALLOW_GROWTH: 'true'
