name: steinbock-snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aioeasywebdav=2.4.0=py38h578d9bd_1001
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.5=py38h2019614_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - amply=0.1.6=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - bcrypt=4.2.0=py38h4005ec7_0
  - boto3=1.35.72=pyhd8ed1ab_0
  - botocore=1.35.99=pyge38_1234567_0
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - coin-or-cbc=2.10.12=h00e76a6_2
  - coin-or-cgl=0.60.9=h82e2f02_4
  - coin-or-clp=1.17.10=h8a7a1e7_1
  - coin-or-osi=0.108.11=h96cc833_4
  - coin-or-utils=2.11.12=h3a12e53_2
  - coincbc=2.10.12=2_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - coloredlogs=15.0.1=pyhd8ed1ab_3
  - configargparse=1.7=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cryptography=43.0.0=py38hf793753_0
  - datrie=0.8.2=py38h01eb140_7
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.20.1=py38h578d9bd_3
  - dpath=2.2.0=pyha770c72_0
  - dropbox=12.0.2=pyhd8ed1ab_0
  - eido=0.2.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - filechunkio=1.8=py_2
  - frozenlist=1.4.1=py38h01eb140_0
  - ftputil=5.1.0=pyhd8ed1ab_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - google-api-core=2.22.0=pyhd8ed1ab_0
  - google-api-python-client=2.151.0=pyhff2d567_0
  - google-auth-httplib2=0.2.0=pyhd8ed1ab_0
  - google-cloud-core=2.4.1=pyhd8ed1ab_0
  - google-cloud-storage=2.18.2=pyhff2d567_0
  - google-crc32c=1.1.2=py38hf9d55a7_5
  - google-resumable-media=2.7.2=pyhd8ed1ab_1
  - googleapis-common-protos=1.65.0=pyhd8ed1ab_0
  - httplib2=0.22.0=pyhd8ed1ab_0
  - humanfriendly=10.0=pyhd8ed1ab_6
  - idna=3.10=pyhd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libabseil=20240116.2=cxx17_he02047a_1
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libgrpc=1.62.2=h15f2491_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblapacke=3.9.0=31_he2f377e_openblas
  - liblzma=5.8.1=hb9d3cd8_0
  - liblzma-devel=5.8.1=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libprotobuf=4.25.3=hd5b35b9_1
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.49.1=hee588c1_2
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - logmuse=0.2.8=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.5=py38h01eb140_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - multidict=6.0.5=py38h01eb140_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - numpy=1.24.4=py38h59b608b_0
  - oauth2client=4.1.3=pyhd8ed1ab_1
  - openssl=3.5.0=h7b32b05_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.0.3=py38h01efb38_1
  - paramiko=3.5.0=pyhd8ed1ab_0
  - pephubclient=0.4.4=pyhd8ed1ab_0
  - peppy=0.40.7=pyhd8ed1ab_1
  - pip=24.3.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - plac=1.4.3=pyhd8ed1ab_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - prettytable=3.11.0=pyhd8ed1ab_0
  - proto-plus=1.25.0=pyhd8ed1ab_0
  - pulp=2.7.0=py38h578d9bd_1
  - pyasn1=0.6.1=pyhd8ed1ab_1
  - pycparser=2.22=pyhd8ed1ab_0
  - pynacl=1.5.0=py38h01eb140_3
  - pyopenssl=24.2.1=pyhd8ed1ab_2
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.3.4=pyhd8ed1ab_0
  - python=3.8.20=h4a871b0_2_cpython
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-irodsclient=2.1.0=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=7_cp38
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0.2=py38h2019614_0
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8c095d6_2
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - s3transfer=0.10.4=pyhd8ed1ab_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - slacker=0.14.0=py_0
  - smart_open=7.0.5=pyhd8ed1ab_1
  - smmap=5.0.0=pyhd8ed1ab_0
  - snakemake=7.32.4=hdfd78af_1
  - snakemake-minimal=7.32.4=pyhdfd78af_1
  - stone=3.3.2=pyhd8ed1ab_0
  - stopit=1.1.2=py_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - toposort=1.10=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typer-slim=0.12.5=pyhd8ed1ab_0
  - typer-slim-standard=0.12.5=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - uritemplate=4.1.1=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_0
  - xz-gpl-tools=5.8.1=hbcc6ac9_0
  - xz-tools=5.8.1=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py38h01eb140_0
  - yte=1.7.0=pyha770c72_1
  - pip:
      - absl-py==2.2.2
      - alabaster==0.7.13
      - anndata==0.9.2
      - anyio==4.5.2
      - app-model==0.2.8
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==25.3.0
      - babel==2.17.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.4
      - bleach==6.1.0
      - build==1.2.2.post1
      - cachetools==5.5.2
      - cachey==0.2.1
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.1.8
      - click-log==0.4.0
      - cloudpickle==3.1.1
      - comm==0.2.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==0.29.37
      - dask==2023.5.0
      - debugpy==1.8.14
      - decorator==5.2.1
      - deepcell==0.12.6
      - deepcell-toolbox==0.12.1
      - deepcell-tracking==0.6.5
      - docstring-parser==0.16
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fcswrite==0.6.2
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - fqdn==1.5.1
      - freetype-py==2.5.1
      - fsspec==2025.3.0
      - gast==0.6.0
      - google-auth==2.39.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.70.0
      - h11==0.16.0
      - h5py==3.11.0
      - heapdict==1.0.1
      - hsluv==5.0.4
      - httpcore==1.0.9
      - httpx==0.28.1
      - igraph==0.11.8
      - imageio==2.35.1
      - imagesize==1.4.1
      - importlib-metadata==8.5.0
      - in-n-out==0.2.1
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.6
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.7
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.14
      - keras==2.8.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - leidenalg==0.10.2
      - libclang==18.1.1
      - llvmlite==0.41.1
      - locket==1.0.0
      - lxml==5.4.0
      - lxml-html-clean==0.4.2
      - magicgui==0.9.1
      - markdown==3.7
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - napari==0.4.19.post1
      - napari-console==0.0.9
      - napari-plugin-engine==0.2.0
      - napari-plugin-manager==0.1.4
      - napari-svg==0.1.10
      - natsort==8.4.0
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nest-asyncio==1.6.0
      - networkx==3.1
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - npe2==0.7.8
      - numba==0.58.1
      - numpydoc==1.7.0
      - oauthlib==3.2.2
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.1
      - pexpect==4.9.0
      - phenograph==1.5.7
      - pickleshare==0.7.5
      - pillow==10.4.0
      - pint==0.21.1
      - pooch==1.8.2
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.51
      - protobuf==3.19.6
      - psutil==7.0.0
      - psygnal==0.11.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1-modules==0.4.2
      - pyconify==0.1.6
      - pydantic==2.10.6
      - pydantic-compat==0.1.2
      - pydantic-core==2.27.2
      - pydot==1.4.2
      - pygments==2.19.1
      - pynndescent==0.5.13
      - pyopengl==3.1.9
      - pyproject-hooks==1.2.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.16
      - pyqt5-sip==12.15.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyzmq==26.4.0
      - qtconsole==5.6.1
      - qtpy==2.4.3
      - readimc==0.8.0
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rpds-py==0.20.1
      - rsa==4.9.1
      - scikit-image==0.19.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - send2trash==1.8.3
      - six==1.17.0
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.7
      - spektral==1.0.6
      - sphinx==7.1.2
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - stack-data==0.6.3
      - steinbock==0.16.3
      - superqt==0.6.7
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.8.4
      - tensorflow-addons==0.16.1
      - tensorflow-estimator==2.8.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.4.0
      - terminado==0.18.1
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - tinycss2==1.2.1
      - tomli==2.2.1
      - tomli-w==1.0.0
      - toolz==1.0.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - triangle==20250106
      - typeguard==4.4.0
      - typer==0.15.3
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - umap-learn==0.5.7
      - uri-template==1.3.0
      - urllib3==2.2.3
      - vispy==0.14.2
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - xtiff==0.7.9
      - zipp==3.20.2
variables:
  STEINBOCK_MASK_DTYPE: uint32
