name: steinbock-snakemake
channels:
  - nvidia/label/cuda-11.3.0
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.6.2=hbcca054_0
  - cuda-nvcc=11.3.58=h2467b9f_0
  - cudatoolkit=11.2.2=hc23eb0c_13
  - cudnn=8.1.0.77=h90431f1_0
  - ld_impl_linux-64=2.40=hf3520f5_3
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h77fa898_8
  - libgomp=13.2.0=h77fa898_8
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_8
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=h4ab18f5_1
  - ncurses=6.5=h59595ed_0
  - openssl=3.3.1=h4ab18f5_0
  - pip=24.0=pyhd8ed1ab_0
  - python=3.9.19=h0755675_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=70.0.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.43.0=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - pip:
      - absl-py==2.1.0
      - alabaster==0.7.16
      - anndata==0.10.7
      - annotated-types==0.7.0
      - anyio==4.4.0
      - app-model==0.2.7
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.7.1
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - build==1.2.1
      - cachetools==5.3.3
      - cachey==0.2.1
      - certifi==2024.6.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-log==0.4.0
      - cloudpickle==3.0.0
      - comm==0.2.2
      - configargparse==1.7
      - connection-pool==0.0.3
      - contourpy==1.2.1
      - cycler==0.12.1
      - cython==0.29.37
      - dask==2024.5.2
      - datrie==0.8.2
      - debugpy==1.8.1
      - decorator==5.1.1
      - deepcell==0.12.6
      - deepcell-toolbox==0.12.1
      - deepcell-tracking==0.6.4
      - defusedxml==0.7.1
      - docstring-parser==0.16
      - docutils==0.21.2
      - dpath==2.2.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - fcswrite==0.6.2
      - flatbuffers==24.3.25
      - fonttools==4.53.0
      - fqdn==1.5.1
      - freetype-py==2.4.0
      - fsspec==2024.6.0
      - gast==0.5.4
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.30.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.64.1
      - h11==0.14.0
      - h5py==3.11.0
      - heapdict==1.0.1
      - hsluv==5.0.4
      - httpcore==1.0.5
      - httpx==0.27.0
      - humanfriendly==10.0
      - idna==3.7
      - imageio==2.34.1
      - imagesize==1.4.1
      - importlib-metadata==7.1.0
      - importlib-resources==6.4.0
      - in-n-out==0.2.1
      - ipykernel==6.29.4
      - ipython==8.18.1
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - keras==2.8.0
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - libclang==18.1.1
      - locket==1.0.0
      - lxml==5.2.2
      - lxml-html-clean==0.1.1
      - magicgui==0.8.3
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - napari==0.4.19.post1
      - napari-console==0.0.9
      - napari-plugin-engine==0.2.0
      - napari-svg==0.1.10
      - natsort==8.4.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - npe2==0.7.5
      - numcodecs==0.12.1
      - numpy==1.23.0
      - numpydoc==1.7.0
      - oauthlib==3.2.2
      - opencv-python-headless==4.10.0.82
      - opt-einsum==3.3.0
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.2
      - pexpect==4.9.0
      - pillow==10.3.0
      - pint==0.23
      - plac==1.4.3
      - platformdirs==4.2.2
      - pooch==1.8.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==3.19.6
      - psutil==5.9.8
      - psygnal==0.11.1
      - ptyprocess==0.7.0
      - pulp==2.7.0
      - pure-eval==0.2.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pyconify==0.1.6
      - pycparser==2.22
      - pydantic==2.7.4
      - pydantic-compat==0.1.2
      - pydantic-core==2.18.4
      - pydot==1.4.2
      - pygments==2.18.0
      - pyopengl==3.1.7
      - pyparsing==3.1.2
      - pyproject-hooks==1.1.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pywavelets==1.6.0
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - readimc==0.7.0
      - referencing==0.35.1
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - reretry==0.11.8
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.1
      - rsa==4.9
      - scikit-image==0.19.3
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - send2trash==1.8.3
      - shellingham==1.5.4
      - six==1.16.0
      - smart-open==7.0.4
      - smmap==5.0.1
      - snakemake==7.32.4
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.5
      - spektral==1.0.6
      - sphinx==7.3.7
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - stack-data==0.6.3
      - steinbock==0.16.3
      - stopit==1.1.2
      - superqt==0.6.7
      - tabulate==0.9.0
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.8.4
      - tensorflow-addons==0.16.1
      - tensorflow-estimator==2.8.0
      - tensorflow-io-gcs-filesystem==0.37.0
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - throttler==1.2.2
      - tifffile==2024.5.22
      - tinycss2==1.3.0
      - tomli==2.0.1
      - tomli-w==1.0.0
      - toolz==0.12.1
      - toposort==1.10
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - typeguard==4.3.0
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.1
      - vispy==0.14.2
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
      - xtiff==0.7.9
      - yte==1.5.4
      - zarr==2.18.2
      - zipp==3.19.2
