name: steinbock-snakemake
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - abseil-cpp=20210324.2=h9c3ff4c_0
  - absl-py=2.1.0=pyhd8ed1ab_0
  - aiohttp=3.9.5=py39hd1e30aa_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - blinker=1.8.2=pyhd8ed1ab_0
  - brotli-python=1.1.0=py39h3d6467e_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.6.2=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.3=pyhd8ed1ab_0
  - certifi=2024.6.2=pyhd8ed1ab_0
  - cffi=1.16.0=py39h7a31438_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cryptography=39.0.0=py39hd598818_0
  - cuda-version=11.0=h6b8d8af_3
  - cudatoolkit=11.0.3=h7761cd4_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - frozenlist=1.4.1=py39hd1e30aa_0
  - gast=0.5.4=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - google-auth=2.30.0=pyhff2d567_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpc-cpp=1.43.2=h9e046d8_3
  - grpcio=1.43.0=py39hff7568b_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=3.9.0=nompi_py39h4dfffb9_100
  - hdf5=1.14.0=nompi_h5231ba7_103
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - jpeg=9e=h0b41bf4_3
  - keras=2.8.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=hf9c8cef_0
  - ld_impl_linux-64=2.40=hf3520f5_3
  - libaec=1.1.3=h59595ed_0
  - libblas=3.9.0=22_linux64_openblas
  - libcblas=3.9.0=22_linux64_openblas
  - libcurl=7.87.0=h6312ad2_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h77fa898_8
  - libgfortran-ng=13.2.0=h69a702a_8
  - libgfortran5=13.2.0=h3d2ce59_8
  - libgomp=13.2.0=h77fa898_8
  - liblapack=3.9.0=22_linux64_openblas
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=3.19.6=h3eb15da_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=13.2.0=hc0a3c3a_8
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=h4ab18f5_6
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py39hd1e30aa_0
  - multidict=6.0.5=py39hd1e30aa_0
  - nccl=2.18.3.1=h17a0586_0
  - ncurses=6.5=h59595ed_0
  - numpy=1.23.0=py39hba7629e_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=1.1.1w=hd590300_0
  - opt_einsum=3.3.0=pyhc1e730c_2
  - pip=24.0=pyhd8ed1ab_0
  - protobuf=3.19.6=py39h227be39_0
  - pyasn1=0.6.0=pyhd8ed1ab_0
  - pyasn1-modules=0.4.0=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.15=h47a2c10_0_cpython
  - python-flatbuffers=24.3.25=pyh59ac667_0
  - python_abi=3.9=4_cp39
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - re2=2022.02.01=h9c3ff4c_0
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=70.0.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hdb0a2a9_1
  - sqlite=3.46.0=h6d4b2fc_0
  - tensorboard=2.8.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.6.1=py39hd97740a_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.8.0=cuda110py39hcfb7b87_0
  - tensorflow-base=2.8.0=cuda110py39h3c9bc52_0
  - tensorflow-estimator=2.8.0=cuda110py39ha53fd0e_0
  - termcolor=2.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - werkzeug=3.0.3=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - wrapt=1.16.0=py39hd1e30aa_0
  - xz=5.2.6=h166bdaf_0
  - yarl=1.9.4=py39hd1e30aa_0
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.22.0=py39h81c9582_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - aiobotocore==2.13.0
      - aioitertools==0.11.0
      - alabaster==0.7.16
      - anndata==0.10.7
      - annotated-types==0.7.0
      - anyio==4.4.0
      - app-model==0.2.7
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-api-compat==1.7.1
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - async-lru==2.0.4
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - botocore==1.34.106
      - build==1.2.1
      - cachey==0.2.1
      - click-log==0.4.0
      - cloudpickle==3.0.0
      - comm==0.2.2
      - configargparse==1.7
      - connection-pool==0.0.3
      - contourpy==1.2.1
      - cycler==0.12.1
      - cython==0.29.37
      - dask==2024.5.2
      - datrie==0.8.2
      - debugpy==1.8.1
      - decorator==5.1.1
      - deepcell==0.12.6
      - deepcell-toolbox==0.12.1
      - deepcell-tracking==0.6.4
      - defusedxml==0.7.1
      - distributed==2024.5.2
      - docstring-parser==0.16
      - docutils==0.21.2
      - dpath==2.2.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - fcswrite==0.6.2
      - fonttools==4.53.0
      - fqdn==1.5.1
      - freetype-py==2.4.0
      - fsspec==2024.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - h11==0.14.0
      - heapdict==1.0.1
      - hsluv==5.0.4
      - httpcore==1.0.5
      - httpx==0.27.0
      - humanfriendly==10.0
      - imageio==2.34.1
      - imagesize==1.4.1
      - importlib-resources==6.4.0
      - in-n-out==0.2.1
      - ipykernel==6.29.4
      - ipython==8.18.1
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.9.25
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - llvmlite==0.42.0
      - locket==1.0.0
      - lxml==5.2.2
      - lxml-html-clean==0.1.1
      - magicgui==0.8.3
      - markdown-it-py==3.0.0
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - msgpack==1.0.8
      - napari==0.4.19.post1
      - napari-console==0.0.9
      - napari-plugin-engine==0.2.0
      - napari-svg==0.1.10
      - natsort==8.4.0
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - npe2==0.7.5
      - numba==0.59.1
      - numcodecs==0.12.1
      - numpydoc==1.7.0
      - opencv-python-headless==4.10.0.82
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.2
      - pexpect==4.9.0
      - pillow==10.3.0
      - pint==0.23
      - plac==1.4.3
      - platformdirs==3.9.0
      - pooch==1.8.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - psutil==5.9.8
      - psygnal==0.11.1
      - ptyprocess==0.7.0
      - pulp==2.7.0
      - pure-eval==0.2.2
      - pyconify==0.1.6
      - pydantic==2.7.4
      - pydantic-compat==0.1.2
      - pydantic-core==2.18.4
      - pydot==1.4.2
      - pygments==2.18.0
      - pyopengl==3.1.7
      - pyparsing==3.1.2
      - pyproject-hooks==1.1.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pywavelets==1.6.0
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - readimc==0.7.0
      - referencing==0.35.1
      - reretry==0.11.8
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.1
      - s3fs==2024.6.0
      - scikit-image==0.19.3
      - scikit-learn==1.5.0
      - send2trash==1.8.3
      - shellingham==1.5.4
      - smart-open==7.0.4
      - smmap==5.0.1
      - snakemake==7.32.4
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - spektral==1.0.6
      - sphinx==7.3.7
      - sphinxcontrib-applehelp==1.0.8
      - sphinxcontrib-devhelp==1.0.6
      - sphinxcontrib-htmlhelp==2.0.5
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.7
      - sphinxcontrib-serializinghtml==1.1.10
      - stack-data==0.6.3
      - steinbock==0.16.3
      - stopit==1.1.2
      - superqt==0.6.7
      - tabulate==0.9.0
      - tblib==3.0.0
      - tensorflow-addons==0.16.1
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - throttler==1.2.2
      - tifffile==2024.5.22
      - tinycss2==1.3.0
      - tomli==2.0.1
      - tomli-w==1.0.0
      - toolz==0.12.1
      - toposort==1.10
      - tornado==6.4.1
      - tqdm==4.66.4
      - traitlets==5.14.3
      - typeguard==4.0.0
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.6.1
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==1.25.4
      - vispy==0.14.2
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.11
      - xtiff==0.7.9
      - yte==1.5.4
      - zarr==2.18.2
      - zict==3.0.0
variables:
  STEINBOCK_MASK_DTYPE: uint32
