projects:
  - test_mcd

# Rule Group 1 : Options for preprocessing IMC Files
# Hot pixel filter
hpf: 5 # hot pixel filter

# Rule Group 2 : Ilastik pixel classification options
cropsize: 512
seed: 123
meanfactor: 100
scale: 2

# Rule Group 3 : CellProfiler
python_path: "/opt/cellprofiler-venv/bin/python"
plugins_path: "/opt/cellprofiler_plugins"

# Rule Group 4 : Deepcell
deepcell_app: "mesmer"
deepcell_model: "MultiplexSegmentation"
deepcell_modelpath: "/opt/keras/models"
deepcell_pxsize: 1

# Rule Group 5 :
aggr: "median"
neighbor_type: "borders"
dmax: 15
kmax: 5
