####################################
# Configuration files for sequanix #
####################################
projects:
  - training# Informs the snakemake pipeline which projects to process

seed: 123L
hpf: 0 # hot pixel filter

nuclear: # Nuclear Channel. For multiple channels the syntax is "Ir191 Ir193 Dy162"
  - ""
cytoplasm: # Cytoplasm Channel. For multiple channels the syntax is "Ir191 Ir193 Dy162"
  - ""
  - ""

deepcell_app: "mesmer"
deepcell_model: "MultiplexSegmentation"
deepcell_modelpath: "/opt/keras/models"
deepcell_pxsize: 1
aggr: "mean" # Aggregation of signal. Can be either of these [mean|median]
neighbor_type: "borders" # Consideration of each neighbor
dmax: 15
kmax: 5

phenograph_k: 30
phenograph_min_cluster_size: 10
