projects:
<<<<<<< HEAD
  - test_mcd_2
=======
  - test_mcd
>>>>>>> 85e6d31392eca4a36304a86dc672577795fd99a7

# Rule Group 1 : Options for preprocessing IMC Files
# Hot pixel filter
hpf: 5 # hot pixel filter

# Rule Group 2 : Ilastik pixel classification options
cropsize: 512
seed: 123
meanfactor: 100
scale: 2

# Rule Group 3 : CellProfiler
python_path: "/opt/cellprofiler-venv/bin/python"
plugins_path: "/opt/cellprofiler_plugins"

# Rule Group 4 : Deepcell
<<<<<<< HEAD
cytoplasm: "Gd160 Ho165"
=======
>>>>>>> 85e6d31392eca4a36304a86dc672577795fd99a7
deepcell_app: "mesmer"
deepcell_model: "MultiplexSegmentation"
deepcell_modelpath: "/opt/keras/models"
deepcell_pxsize: 1

# Rule Group 5 :
aggr: "median"
neighbor_type: "borders"
dmax: 15
kmax: 5
